CarFiller
skieylion/nikita pull request #10
Opened 2023-12-20 14:31 UTC by Feylor

2023-12-20 17:03 UTC, skieylion requested changes

2023-12-20 17:03 UTC, skieylion commented on src/main/java/ru/nikita/tasks/CarFiller.java
> +        car.setModel("BMW", "SP827S");
number отдельно

2023-12-20 17:03 UTC, skieylion commented on src/main/java/ru/nikita/tasks/CarFiller.java
> +    void fillEngine(Engine engine) {
Двигатель ннужно заполнять в отдельном классе

2023-12-20 17:03 UTC, skieylion commented on src/main/java/ru/nikita/tasks/Cube.java
> +        this.height = "Высота";
Здесь числа должны быть. И их нужно получать из параметров конструктора

2023-12-21 17:10 UTC, skieylion requested changes

2023-12-21 17:10 UTC, skieylion commented on src/main/java/ru/nikita/tasks/Cube.java
> +        this.height = 2;
нет, нам конструктор нужен для начальной инициализации. Поэтому должно быть Car(height, length,width)

2023-12-21 17:10 UTC, skieylion commented on src/main/java/ru/nikita/tasks/EngineFiller.java
> +        engine.volume = 3.999;
тебе нужен конструктор для Engine, чтобы туда передать все эти параметры

2023-12-21 17:10 UTC, skieylion commented on src/main/java/ru/nikita/tasks/EngineFiller.java
> +        engine.setActive(true);
если ты хочешь запустить двигатель, то тебе нужно сначала запустить машину. Из этого места не нужно управлять запуском двигятеля. Это просто заполнитель параметров

2023-12-21 17:10 UTC, skieylion commented on src/main/java/ru/nikita/tasks/CarFiller.java
> +        car.colour = "Blue";
везде сеттеры, а здесь почему-то прямой доступ к переменной. Если захочу изменить изменение параметра, то мне придётся во всех местах  это делать ? логичнее засунуть в сеттер

2023-12-21 17:10 UTC, skieylion commented on src/main/java/ru/nikita/tasks/CarFiller.java
> +    Car car;
зачем тебе здесь car ?

2023-12-21 17:10 UTC, skieylion commented on src/main/java/ru/nikita/tasks/CarFiller.java
> +        car = new Car();
я так и не понял зачем он тебе нужен здесь

2023-12-21 17:10 UTC, skieylion commented on src/main/java/ru/nikita/tasks/EngineFiller.java
> +    Engine engine;
зачем тебе двигатель здесь

2023-12-21 17:10 UTC, skieylion commented on src/main/java/ru/nikita/tasks/EngineFiller.java
> +        engine = new Engine();
зачем создавать объект двигателя

2023-12-21 17:39 UTC, skieylion requested changes
Слишком много однотипных ошибок при каждом ревью. Смотри шаблоны как программируют сеттеры, геттеры и конструкторы. Найди закономерности применения паттернов и делай также

2023-12-21 17:39 UTC, skieylion commented on src/main/java/ru/nikita/tasks/Cube.java
> +        this.height = 2;
А мы для кого конструктор делали с параметрами

2023-12-21 17:39 UTC, skieylion commented on src/main/java/ru/nikita/tasks/Cube.java
> +        this.height = 2;
Проблема не решена

2023-12-21 17:39 UTC, skieylion commented on src/main/java/ru/nikita/tasks/Engine.java
> +    Engine engine;
Зачем тебе двигатель внутри двигателя?

2023-12-21 17:39 UTC, skieylion commented on src/main/java/ru/nikita/tasks/Engine.java
> +        engine = new Engine();
Ты что хочешь зациклить?

2023-12-21 17:39 UTC, skieylion commented on src/main/java/ru/nikita/tasks/EngineFiller.java
> +    EngineFiller() {
Зачем тебе здесь пустой конструктор

2023-12-21 17:39 UTC, skieylion commented on src/main/java/ru/nikita/tasks/EngineFiller.java
> +        engine.volume = 3.999;
А для кого ты делал конструктор с параметрами ?

2023-12-21 17:39 UTC, Feylor commented on src/main/java/ru/nikita/tasks/Cube.java
> +        this.height = 2;
Для Куба

2023-12-23 13:36 UTC, skieylion requested changes

2023-12-23 13:36 UTC, skieylion commented on src/main/java/ru/nikita/tasks/Cube.java
> +    public void volume(double volume){
А как я значение получу? Сам попробуй вызвать этот метод и выведи в консоль какой объем куба

2023-12-23 13:36 UTC, skieylion commented on src/main/java/ru/nikita/tasks/EngineFiller.java
> +        engine.volume = 3.999;
Сделай конструктор в Engine, чтобы передать туда параметры

2023-12-24 10:07 UTC, skieylion requested changes

2023-12-24 10:07 UTC, skieylion commented on src/main/java/ru/nikita/tasks/App.java
> +        cube.width = 2;
прямой доступ к переменной - нужно убрать или заменить на сеттер

2023-12-24 10:07 UTC, skieylion commented on src/main/java/ru/nikita/tasks/Engine.java
>      int power; // Мощность двигателя
избыточный комментарий. если пишешь комментарий к переменной, то это сигнал к тому, что переменную назвал неправильно

2023-12-24 10:07 UTC, skieylion commented on src/main/java/ru/nikita/tasks/Engine.java
>      int cost; // Затраты двигателя n км/л
аналогично

2023-12-24 10:13 UTC, skieylion approved these changes
good job

2023-12-24 10:13 UTC, merged