solution
skieylion/nikita pull request #9
Opened 2023-12-16 20:18 UTC by Kamirisu

2023-12-16 20:47 UTC, skieylion requested changes
You need to improve your code. I request that you do not omit my comments

2023-12-16 20:47 UTC, skieylion commented on Study/src/Main.java
> +        /* 1.1
зачем нужен этот комментарий ?

2023-12-16 20:47 UTC, skieylion commented on Study/src/Main.java
> +        //3.3
избыточный комментарий

2023-12-16 20:47 UTC, skieylion commented on Study/src/Main.java
> +        MathUtils.getFactorial(Constants.pi);
Константы с большой буквы указываются

2023-12-16 20:47 UTC, skieylion commented on Study/src/Main.java
> +        //4
избыточный комментарий. Лучше в отдельных методах сделай

2023-12-16 20:47 UTC, skieylion commented on Study/src/Main.java
> +        sum.printDetails("Mila", "Milushka", "Milka");
сразу же нарушение принципов SOLID, а именно Single Responsibility Principle. Класс и печает и суммирует.

2023-12-16 20:47 UTC, skieylion commented on Study/src/MathUtils.java
> +public class MathUtils {
public final class MathUtils

2023-12-16 20:47 UTC, skieylion commented on Study/src/MathUtils.java
> +        else max = y;
а смысл, когда можно сделать return y

2023-12-16 20:47 UTC, skieylion commented on Study/src/MathUtils.java
> +            max = x;
а смысл, когда можно сделать return x

2023-12-16 20:47 UTC, skieylion commented on Study/src/Sum.java
> +    public class Sum {
3 метода print... и sum . Это скорее класс не Sum, а Printer
Почитай про [солид](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8)

2023-12-16 20:47 UTC, skieylion commented on Study/src/Student.java
> +    public static void fillStudentData(Student object, String name, int age, String major, String grades) {
кто такой object ?

2023-12-16 20:47 UTC, skieylion commented on Study/src/Main.java
> +        Scanner sc = new Scanner(System.in);
сделай отдельные методы для этих целей

2023-12-16 20:47 UTC, skieylion commented on Study/src/Main.java
> +        Calculator calc = new Calculator(num1, num2, operation);
Как-то неудобно делать класс калькулятор, но зашивать в него одну операцию. Лучше сделать класс и статические методы: add,substruct, divide, multiply

2023-12-16 20:47 UTC, skieylion commented on Study/src/Calculator.java
> +                break;
а смысл, можно просто return num1*num2

2023-12-16 20:47 UTC, skieylion commented on Study/src/Calculator.java
> +        return answer;
ну и если у меня операция будет не подходить, то зачем мне 0 и почему именно 0 ? как я отличать буду реальное умножение 0/78 при operation '/' от 100*100 при operation 'fuck'

2023-12-16 20:47 UTC, skieylion commented on Study/src/Change.java
> +    public Change(int x){
что это за пустой конструктор с параметром ?

2023-12-16 20:47 UTC, skieylion commented on Study/src/Change.java
> +public class Change {
не понимаю, что за change . Это класс меняет мир к лучшему ?

2023-12-16 20:47 UTC, skieylion commented on Study/src/Change.java
> +    int x;
почему x ? что это вообще за икс, не понимаю его предназначение

2023-12-16 20:47 UTC, skieylion commented on Study/src/Change.java
> +    public void tryChange(int x){
почему tryChange ? он что может и не прибавить к x + 1 ?

2023-12-16 20:47 UTC, skieylion commented on Study/src/Change.java
> +    public int getX(){
почему икс, почему не getFuck ?

2023-12-16 20:47 UTC, skieylion commented on Study/src/Constants.java
> +public class Constants {
public final class

2023-12-16 20:47 UTC, skieylion commented on Study/src/Constants.java
> +    public static final double pi = 3.14;
PI (константы пишут в верхнем регистре)

2023-12-16 20:47 UTC, skieylion commented on Study/src/ImmutablePoint.java
> +    final int x1;
почему x1, а не xFuck ? аналогично и y

2023-12-16 20:47 UTC, skieylion commented on Study/src/ImmutablePoint.java
> +        x1 = 12;
почему захардкожено ?

2023-12-16 20:47 UTC, skieylion commented on Study/src/ImmutablePoint.java
> +    public int getX1(){
да почему X ,а не Fuck ?

2023-12-16 20:47 UTC, skieylion commented on Study/src/Main.java
> +        sum.printInfo("mur", " mur");
почему printInfo ?
что за info ? 
сделай по аналогии с System.out.print

2023-12-16 20:47 UTC, skieylion commented on Study/src/Student.java
> +    public static void fillStudentData(Student object, String name, int age, String major, String grades) {
Зачем ему метод, который всё заполняет ? Это лучше сделать в отдельном методе ну или через конструктор, который заполняет все параметры в Student

2023-12-16 20:47 UTC, skieylion commented on Study/src/Sum.java
> +            System.out.print(text);
И в чём смысл от этого метода ? Почему бы System.out.print(text); не использовать ?

2023-12-16 20:47 UTC, skieylion commented on Study/src/Sum.java
> +    static void printInfo(String... info) {
Чем printInfo отличается от printDetails кроме названия ?

2023-12-17 15:03 UTC, Kamirisu commented on Study/src/Student.java
> +    public static void fillStudentData(Student object, String name, int age, String major, String grades) {
почему лучше сделать в отдельном методе (другой класс)

2023-12-17 16:52 UTC, Kamirisu commented on Study/src/ImmutablePoint.java
> +    final int x1;
задача 3.2
>создайте класс  ImmutablePoint с final полями x и y

2023-12-17 17:13 UTC, Kamirisu commented on Study/src/Main.java
> +        sum.printInfo("mur", " mur");
не поняла что нужно
>сделай по аналогии с System.out.print

2023-12-18 17:31 UTC, skieylion commented on Study/src/Main.java
> +        sum.printInfo("mur", " mur");
методы print... перенеси в отдельный класс и сделай из статическими

2023-12-18 17:36 UTC, skieylion commented on Study/src/Student.java
> +    public static void fillStudentData(Student object, String name, int age, String major, String grades) {
Это метод, который заполняет student. Для заполнения объекта есть сеттеры, а ещё можно сделать конструктор. Здесь подразумевается отдельная логика для заполнения объекта. Например сделать куда-нибудь запрос. Вытащить данные из файла. Указать какой-то определенный формат при заполнении. Например символы в верхнем регистре. Для этого лучше сделать отдельный класс, который будет заполнять объект. Если нужно просто присвоить параметры, то это есть инициализация, а для инициализации используется конструктор. Но тебе нужно заполнить через отдельный класс. Сделай, чтобы name заполнялся в нижнем регистре, но первая буква имени с большой

2023-12-21 20:54 UTC, skieylion requested changes

2023-12-21 20:54 UTC, skieylion commented on Study/src/Calculator.java
> +    public Calculator(int num1, int num2) {
Так зачем инкапсулировать значения. Если у меня будут другие значения, то мне опять класс создавать нужно будет ? Или юзать сеттеры, а потом метод вычисления ? Не проще сделать Calculator.add(3,5) ? Метод будет возвращать сумму, а Calculator.substruct(5,10) будет вычислять разность. А если у меня 1_000_000 операций, то мне что нужно будет создать миллион объектов (что-то накладно выходит)? А если я в разных потоках работаю, то мне как тогда здесь быть ? 
1. Слишком сложно, 2. Не пригодно для многопоточки

2023-12-21 20:54 UTC, skieylion commented on Study/src/Calculator.java
> +    public int add() {
в add нужно аргументы указать, а также во все остальные

2023-12-21 20:54 UTC, skieylion commented on Study/src/CalculatorAdd.java
>  public class CalculatorAdd
Теперь вообще не понял. А зачем нам этот класс ? У нас вроде есть сложение в Calculator

2023-12-21 20:54 UTC, skieylion commented on Study/src/CalculatorAdd.java
>      double add(int a, int b, int c) {
Ну уж тогда varargs используй, но опять же это нужно сделать в Calculator

2023-12-21 20:54 UTC, skieylion commented on Study/src/FillStudents.java
> +public class FillStudents {
FillStudent. Одного студента заполняешь

2023-12-21 20:54 UTC, skieylion commented on Study/src/ImmutablePoint.java
> +    public int getX(){
а где getY ?

2023-12-21 20:54 UTC, skieylion commented on Study/src/Main.java
> +        // 2.1 Создайте метод, который принимает целочисленный аргумент и изменяет его значение внутри метода
этот комментарий нужно над методом использовать, используя JavaDoc

2023-12-21 20:54 UTC, skieylion commented on Study/src/Main.java
> +        MathUtils.getFactorial(Constants.PI);
А зачем тогда метод отдельный нужен ?

2023-12-21 20:54 UTC, skieylion commented on Study/src/MathUtils.java
> +        }
} else { ... в одной строчке. так принято писать

2023-12-21 20:54 UTC, skieylion commented on Study/src/Plus1.java
> +public class Plus1 {
Зачем этот класс когда есть Calculator

2023-12-21 20:54 UTC, skieylion commented on Study/src/Printer.java
> +            System.out.print(detail);
Просто добавь + " " вместо доп функции

2023-12-21 20:54 UTC, skieylion commented on Study/src/Printer.java
> +    //5.1 Создайте перегруженные версии метода (например, 'printInfo'), одна версия которого использует varargs, а другая — фиксированное количество аргументов.
java doc

2023-12-21 20:54 UTC, skieylion commented on Study/src/Printer.java
> +            System.out.print(inf);
Те же замечания, а почему-бы не объединить с printDetails ? Они вроде одно и то же действие делают

2023-12-21 20:54 UTC, skieylion commented on Study/src/Printer.java
> +    static void printInfo(String text1, String text2) {
А в чем смысл когда есть вараргс, который также залогирует

2023-12-21 20:54 UTC, skieylion commented on Study/src/Student.java
> +    public String toUpper(String name){
такое ощущение, что весь name в верхний регистр. withFirstSymbpolAsUpper

2023-12-21 20:54 UTC, skieylion commented on Study/src/Sum.java
>      public class Sum {
убери этот класс. Есть Calculator

2023-12-21 20:54 UTC, skieylion commented on Study/src/Sum.java
>          for (int value : args) {
лучше добавить метод sum в Calcilator и сложить все числа, ну или add с varargs

2023-12-22 16:08 UTC, skieylion requested changes

2023-12-22 16:08 UTC, skieylion commented on Study/src/Calculator.java
> +    public static int add( int... args) {
А если я null передам, то всё сломается. Сделай проверку если null, то вернуть 0

2023-12-22 16:08 UTC, skieylion commented on Study/src/Calculator.java
> +            resultSum = resultSum + value;
+=

2023-12-22 16:08 UTC, skieylion commented on Study/src/Rectangle.java
> +    Rectangle(int width){
прямоугольник с 1 стороной это как ?

2023-12-22 16:08 UTC, skieylion commented on Study/src/Rectangle.java
> +        this.width = 6;
а зачем хардкодить числа здесь ?

2023-12-22 16:08 UTC, skieylion commented on Study/src/Printer.java
> +        for (String inf : info) {
я бы не хотел здесь упасть если info придёт null

2023-12-24 22:48 UTC, skieylion requested changes

2023-12-24 22:48 UTC, skieylion commented on Study/src/Calculator.java
> +    public static int substruct(int num1, int num2) {
Эти по аналогии с add

2023-12-24 22:48 UTC, skieylion commented on Study/src/Calculator.java
> +    public static int divide(int num1, int num2) {
Этот тоже

2023-12-24 22:48 UTC, skieylion commented on Study/src/Calculator.java
> +    public static int multiply(int num1, int num2) {
И этот

2023-12-24 22:48 UTC, skieylion commented on Study/src/MathUtils.java
> +    public static double getFactorial(double a) {
1. У тебя некорректно вычисляется факториал вещественного числа 
2. В задаче имеются ввиду целые числа. Для целых чисел корректно вычисляется

2023-12-24 22:48 UTC, skieylion commented on Study/src/Parallelogram.java
> +    Parallelogram(double side1, double height) {
Что такое side1? Почему не side100500?

2023-12-24 22:48 UTC, skieylion commented on Study/src/Parallelogram.java
> +    double side2;
Зачем мне side2 если в конструкторе используется side1?

2023-12-24 22:48 UTC, skieylion commented on Study/src/Parallelogram.java
> +    double angle;
В чем измеряется угол? В бубликах?

2023-12-24 22:48 UTC, skieylion commented on Study/src/Parallelogram.java
> +    public static double area(double side1,double side2, double angle){
В методах принято указывать глаголы

2023-12-24 22:48 UTC, skieylion commented on Study/src/Parallelogram.java
> +    public static double area(double side1,double side2, double angle){
Зачем мне статический метод, а на кой я тебе в конструкторы передаю параметры?

2023-12-24 22:48 UTC, skieylion commented on Study/src/Parallelogram.java
> +    public static double area(double side1, double height){
Статические методы нужны для общих действий над однотипными объектами. У тебя же получение площади в контексте конкретной фигуры

2023-12-24 22:48 UTC, skieylion commented on Study/src/Parallelogram.java
> +        return (side1 * height);
Нафиг здесь скобочки

2023-12-24 22:48 UTC, skieylion commented on Study/src/Printer.java
> +    static void printInfo(String... info) {
Что за info печатается? Газета какая-то что-ли или шо?

2023-12-24 22:48 UTC, skieylion commented on Study/src/Rectangle.java
> +    Rectangle(double diagonal, double angle) {
Зачем прямоугольнику угол? Там разве не прямой угол?

2023-12-24 22:48 UTC, skieylion commented on Study/src/Rectangle.java
> +    public static double area(double diagonal, double angle){
А зачем тут угол?

2023-12-24 22:48 UTC, skieylion commented on Study/src/Rectangle.java
> +        return (0.5 * diagonal * diagonal * Math.sin(Math.toRadians(angle)));
Зачем тебе здесь угол когда у прямоугольника он всегда прямой

2023-12-24 22:48 UTC, skieylion commented on Study/src/Square.java
> +    int side;
А что сторона может быть только целым числом?

2023-12-28 19:06 UTC, skieylion approved these changes
Ok. But you need to use camel case notation to name your methods

2023-12-28 19:07 UTC, merged